#!/usr/bin/env python3
"""The Level 1 survey (TODO.md 10.4; FR-BRG-002): how often a real Odum graph is in exponential form,
and what the kernel's integrators lose against the exact exponential when it is.

Verifies: FR-BRG-002 (T-BRG-02)

For every model in examples/*.json this runs bin/gia_bridge and records:
  - coverage: the fraction the projection carries (gia_project);
  - exponential form: every pathway law is linear in the state (linear, reversible, constant) and no
    pathway rate is forced, so dQ/dt = A Q + b(t) with b generated by the source waveforms, and
    exp(A t) on the augmented state is the exact solution;
  - for a model carried whole: the kernel's largest scaled difference from the Giannantoni
    engine's exp(A t) -- |kernel - exact| over the node's largest magnitude in the run, maximised
    over nodes and steps -- under the model's own method and under rk4, euler and expm, at its own
    dt. (Scaled, not pointwise relative: a store at exactly 0 on one side and 1e-9 on the other is
    a relative difference of 1.)

examples/invalid_model.json is the kernel's deliberately unloadable fixture and is not surveyed.

  python3 -I scripts/level1_survey.py            # print the table
  python3 -I scripts/level1_survey.py --check F  # fail if F disagrees with a fresh run

Differences are written to 3 significant figures, and anything below 1e-12 as "< 1e-12", which is
at rounding level and may differ between toolchains.
"""
import glob
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRIDGE = os.environ.get("BRIDGE", os.path.join(ROOT, "bin", "gia_bridge"))
LINEAR = {"linear", "reversible", "constant"}
METHODS = ["rk4", "euler", "expm"]


def bridge(model, method=None):
    cmd = [BRIDGE, model] + (["--method", method] if method else [])
    p = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    kv = {}
    for line in p.stdout.splitlines():
        if ": " in line and not line.startswith(" "):
            k, v = line.split(": ", 1)
            kv[k] = v
    return p.returncode, kv


def fmt(x):
    x = float(x)
    return "< 1e-12" if x < 1e-12 else "%.2e" % x


def survey():
    rows = []
    for path in sorted(glob.glob(os.path.join(ROOT, "examples", "*.json"))):
        if os.path.basename(path) == "invalid_model.json":
            continue
        rel = os.path.relpath(path, ROOT)
        name = os.path.basename(path)[:-5]
        with open(path) as f:
            d = json.load(f)
        edges = d.get("edges", [])
        logics = sorted({e.get("logic", "linear") for e in edges})
        exp_form = all(l in LINEAR for l in logics) and not any("forcing" in e for e in edges)
        rc, kv = bridge(rel)
        if rc == 1:
            rows.append((name, "does not load", "—", "—", "—", "—", "—", "—"))
            continue
        cov = kv.get("bridge.coverage", "?")
        own = d.get("config", {}).get("method", "auto")
        if rc == 2:
            rows.append((name, cov, "yes" if exp_form else "no", own, "—", "—", "—", "—"))
            continue
        diffs = [fmt(kv["bridge.max_scaled_difference"])]
        for m in METHODS:
            rcm, kvm = bridge(rel, m)
            diffs.append(fmt(kvm["bridge.max_scaled_difference"]) if rcm == 0 else "fails")
        rows.append((name, cov, "yes" if exp_form else "no", own, *diffs))
    return rows


HEADER = ("| Model | Coverage | Exponential form | Own method | Own | RK4 | Euler | expm |\n"
          "|---|---|---|---|---|---|---|---|\n")


def render(rows):
    whole = [r for r in rows if r[1] == "100.0%"]
    expf = [r for r in rows if r[2] == "yes"]
    both = [r for r in whole if r[2] == "yes"]
    out = ["# Level 1 survey: how often is an Odum graph in exponential form?\n",
           "Generated by `python3 -I scripts/level1_survey.py` (`make level1-survey`), and checked "
           "against a fresh run in CI (`make check-level1`, T-BRG-02). Do not edit by hand.\n",
           "## The numbers\n",
           "- **%d** kernel examples (all but `invalid_model`, the kernel's deliberately unloadable "
           "fixture). **%d** of them are carried whole by the projection." % (len(rows), len(whole)),
           "- **%d** are in exponential form: every pathway law is linear in the state, and no "
           "pathway rate is forced. **%d** are both in exponential form and carried whole." % (len(expf), len(both)),
           "- The other **%d** need a law the projection does not carry, or a forcing no generator "
           "carries. They are listed in the table below, and the coverage report names each blocker "
           "(`bin/gia_bridge <model>`).\n" % (len(rows) - len(whole)),
           "## The table\n",
           "For a model carried whole, the four right-hand columns give the kernel's largest "
           "**scaled** difference from the Giannantoni engine's `exp(A t)` at the model's own `dt`: "
           "`|kernel − exact|` over the node's largest magnitude in the run, maximised over nodes and "
           "steps. The first is under the model's own method, then RK4, Euler and the kernel's own "
           "Padé `expm`.\n",
           "These are classical numbers: the kernel integrator's error against the exact "
           "exponential. They are not incipient drift; both engines' trajectories are classical "
           "(PLAN.md §2 E3).\n",
           HEADER.rstrip("\n")]
    for r in rows:
        out.append("| `%s` | %s |" % (r[0], " | ".join(r[1:])))
    out.append("")
    out.append("## Reading it\n")
    out.append("- **Not in exponential form, but carried whole** (`supply_chain_30`, "
               "`three_input_gate_model`). Their interaction or subtract laws are not linear in the "
               "state. The two engines then agree only as closely as both solve the same nonlinear "
               "system, so the difference is no longer one integrator's error.")
    out.append("- **The kernel's `expm` is exact only when the system is autonomous.** It holds a "
               "source's forcing fixed across each step. The bridge's sine-forced fixture "
               "(`tests/fixtures/bridge_sine_source.json`, not an example) shows the cost: about "
               "0.4% at `dt = 0.5`, where RK4 is at about 1e-9.")
    out.append("")
    return "\n".join(out)


def main():
    text = render(survey())
    if len(sys.argv) == 3 and sys.argv[1] == "--check":
        with open(sys.argv[2]) as f:
            committed = f.read()
        if committed != text:
            import difflib
            sys.stdout.writelines(difflib.unified_diff(committed.splitlines(True), text.splitlines(True),
                                                       "committed", "fresh run"))
            print("check-level1: %s disagrees with a fresh run (regenerate: make level1-survey)" % sys.argv[2])
            return 1
        print("check-level1: OK -- %s matches a fresh run" % sys.argv[2])
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
